/**
 * Generates docs/authorization-matrix.md and docs/endpoint-coverage.md.
 *
 * Generated rather than hand-written so they cannot drift from the code. A
 * hand-maintained authorization matrix is wrong the first time anyone changes a
 * profile, and a wrong security document is worse than none.
 *
 * Run: npm run docs:generate
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { createFeatureFlags } from '../src/config/feature-flags.js';
import { UNPROBED } from '../src/core/authorization/capabilities.js';
import { createPrincipal } from '../src/core/authorization/principal.js';
import { ROLE_PROFILES, reachableScopeFor } from '../src/core/authorization/role-profiles.js';
import { ENDPOINT_MANIFEST, SNAPSHOT_VERSION } from '../src/core/jisr/endpoint-manifest.js';
import { registerReadTools } from '../src/core/tools/index.js';
import { ToolRegistry } from '../src/core/tools/registry.js';

const DOCS = resolve(process.cwd(), 'docs');
const GENERATED = '<!-- GENERATED by scripts/generate-docs.ts. Do not edit by hand. -->';

function surfaceFor(profile: (typeof ROLE_PROFILES)[number], finance: boolean): Set<string> {
  const registry = new ToolRegistry();
  registerReadTools(registry);
  return new Set(
    registry
      .listFor({
        principal: createPrincipal({ organizationId: 'doc', profile }),
        flags: createFeatureFlags({ financeSurfaceEnabled: finance }),
        observed: UNPROBED,
      })
      .map((tool) => tool.name),
  );
}

async function authorizationMatrix(): Promise<void> {
  const registry = new ToolRegistry();
  registerReadTools(registry);
  const tools = registry
    .all()
    .map((t) => t.name)
    .sort();

  const rows = tools.map((tool) => {
    const cells = ROLE_PROFILES.map((profile) => {
      const off = surfaceFor(profile, false).has(tool);
      const on = surfaceFor(profile, true).has(tool);
      if (off && on) return '✅';
      if (!off && on) return '🔓'; // requires the finance surface
      return '—';
    });
    return `| \`${tool}\` | ${cells.join(' | ')} |`;
  });

  const reach = ROLE_PROFILES.map(
    (profile) => `| \`${profile}\` | ${reachableScopeFor(profile)} |`,
  );

  await writeFile(
    resolve(DOCS, 'authorization-matrix.md'),
    `# Authorization matrix

${GENERATED}

Which tools each role profile can see and call. A tool absent from a profile's
surface is **undiscoverable**, not merely refused — it does not appear in
\`tools/list\` at all (spec FR-018).

**Legend:** ✅ available · 🔓 available only when the operator has explicitly
enabled the finance surface · — not available

| Tool | ${ROLE_PROFILES.map((p) => `\`${p}\``).join(' | ')} |
|---|${ROLE_PROFILES.map(() => '---').join('|')}|
${rows.join('\n')}

## Record reachability

Authorization decides whether a profile may run a tool. Reachability decides
which **records** that call returns, applied before pagination (spec FR-018a).

| Profile | Reachable records |
|---|---|
${reach.join('\n')}

\`direct_reports\` means an employee whose \`line_manager\` resolves to the
caller. No indirect reporting tree is derived: Jisr exposes a single-level
\`line_manager\`, so a wider tree would have to be inferred and then trusted for
an authorization decision (spec FR-019a).
`,
    'utf8',
  );
}

async function endpointCoverage(): Promise<void> {
  const reads = ENDPOINT_MANIFEST.filter((e) => e.release === 1 && e.readOrWrite === 'read');
  const writes = ENDPOINT_MANIFEST.filter((e) => e.release === 2);
  const auth = ENDPOINT_MANIFEST.filter((e) => e.release === 1 && e.readOrWrite === 'write');

  const row = (e: (typeof ENDPOINT_MANIFEST)[number]): string =>
    `| \`${e.method}\` | \`${e.path}\` | ${e.implementedTool === null ? '—' : `\`${e.implementedTool}\``} | ${e.sensitivity.replace(/_/g, ' ')} |`;

  await writeFile(
    resolve(DOCS, 'endpoint-coverage.md'),
    `# Endpoint coverage

${GENERATED}

Against Jisr OpenAPI snapshot **${SNAPSHOT_VERSION}**.
\`npm run verify:coverage\` fails the build if this diverges.

**${ENDPOINT_MANIFEST.length}** documented operations: ${reads.length} reads implemented,
${writes.length} writes deliberately unbound, ${auth.length} handled internally.

## Release 1 — implemented reads (${reads.length})

| Method | Path | Tool | Sensitivity |
|---|---|---|---|
${reads.map(row).join('\n')}

## Handled internally (${auth.length})

Never exposed as a tool: doing so would put credentials in a tool contract.

| Method | Path | Tool | Sensitivity |
|---|---|---|---|
${auth.map(row).join('\n')}

## Release 2 — known and unbound (${writes.length})

Recorded so the coverage gate can assert these are *unimplemented* rather than
*missed*. This release has no write surface: no tool, no client method, no code
path (spec FR-012).

| Method | Path | Tool | Sensitivity |
|---|---|---|---|
${writes.map(row).join('\n')}
`,
    'utf8',
  );
}

async function main(): Promise<void> {
  await mkdir(DOCS, { recursive: true });
  await authorizationMatrix();
  await endpointCoverage();
  console.log('Generated docs/authorization-matrix.md and docs/endpoint-coverage.md');
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
